# Generated by Django 3.0 on 2022-02-22 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userId', models.IntegerField(default=1)),
                ('title', models.CharField(default='Default Title', max_length=200)),
                ('body', models.TextField(default='Body of post goes here')),
            ],
        ),
    ]
